// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa29EQtYYzcOA9PAgNF6ytk3vLpny8xSM',
    appId: '1:998108968915:web:111d38aa92d7579081e126',
    messagingSenderId: '998108968915',
    projectId: 'copy-coffee',
    authDomain: 'copy-coffee.firebaseapp.com',
    storageBucket: 'copy-coffee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYWCH9SpDVrcyI4GVvtK68j5Wfm2LIr90',
    appId: '1:998108968915:android:538fed416295b7aa81e126',
    messagingSenderId: '998108968915',
    projectId: 'copy-coffee',
    storageBucket: 'copy-coffee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4YLsTz3739SCfv3tfWihk5RgpcS5ys4U',
    appId: '1:998108968915:ios:96f797b18a50ac0181e126',
    messagingSenderId: '998108968915',
    projectId: 'copy-coffee',
    storageBucket: 'copy-coffee.appspot.com',
    iosClientId: '998108968915-19sg3t5d9ahifqapfm423njclsq3on6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.copy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4YLsTz3739SCfv3tfWihk5RgpcS5ys4U',
    appId: '1:998108968915:ios:96f797b18a50ac0181e126',
    messagingSenderId: '998108968915',
    projectId: 'copy-coffee',
    storageBucket: 'copy-coffee.appspot.com',
    iosClientId: '998108968915-19sg3t5d9ahifqapfm423njclsq3on6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.copy',
  );
}
